package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuborder<M extends BaseSuborder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public void setWareId(java.lang.String wareId) {
		set("wareId", wareId);
	}

	public java.lang.String getWareId() {
		return get("wareId");
	}

	public void setWareName(java.lang.String wareName) {
		set("wareName", wareName);
	}

	public java.lang.String getWareName() {
		return get("wareName");
	}

	public void setWareAmount(java.math.BigDecimal wareAmount) {
		set("wareAmount", wareAmount);
	}

	public java.math.BigDecimal getWareAmount() {
		return get("wareAmount");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setMinutes(java.lang.Integer minutes) {
		set("minutes", minutes);
	}

	public java.lang.Integer getMinutes() {
		return get("minutes");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setAutoTimestamp(java.util.Date autoTimestamp) {
		set("autoTimestamp", autoTimestamp);
	}

	public java.util.Date getAutoTimestamp() {
		return get("autoTimestamp");
	}

}
