package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWare<M extends BaseWare<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setWareId(java.lang.String wareId) {
		set("wareId", wareId);
	}

	public java.lang.String getWareId() {
		return get("wareId");
	}

	public void setWareName(java.lang.String wareName) {
		set("wareName", wareName);
	}

	public java.lang.String getWareName() {
		return get("wareName");
	}

	public void setWarePrice(java.math.BigDecimal warePrice) {
		set("warePrice", warePrice);
	}

	public java.math.BigDecimal getWarePrice() {
		return get("warePrice");
	}

	public void setShopId(java.lang.String shopId) {
		set("shopId", shopId);
	}

	public java.lang.String getShopId() {
		return get("shopId");
	}

	public void setBuzLine(java.lang.Integer buzLine) {
		set("buzLine", buzLine);
	}

	public java.lang.Integer getBuzLine() {
		return get("buzLine");
	}

	public void setCateId(java.lang.String cateId) {
		set("cateId", cateId);
	}

	public java.lang.String getCateId() {
		return get("cateId");
	}

	public void setCateName(java.lang.String cateName) {
		set("cateName", cateName);
	}

	public java.lang.String getCateName() {
		return get("cateName");
	}

	public void setWareStatus(java.lang.Integer wareStatus) {
		set("wareStatus", wareStatus);
	}

	public java.lang.Integer getWareStatus() {
		return get("wareStatus");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return get("brand");
	}

	public void setSpecial(java.lang.String special) {
		set("special", special);
	}

	public java.lang.String getSpecial() {
		return get("special");
	}

	public void setShelfLife(java.lang.String shelfLife) {
		set("shelfLife", shelfLife);
	}

	public java.lang.String getShelfLife() {
		return get("shelfLife");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setWareDetail(byte[] wareDetail) {
		set("wareDetail", wareDetail);
	}

	public byte[] getWareDetail() {
		return get("wareDetail");
	}

	public void setIsPromotion(java.lang.Integer isPromotion) {
		set("isPromotion", isPromotion);
	}

	public java.lang.Integer getIsPromotion() {
		return get("isPromotion");
	}

	public void setIsIndex(java.lang.Integer isIndex) {
		set("isIndex", isIndex);
	}

	public java.lang.Integer getIsIndex() {
		return get("isIndex");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.Integer getCreateUserId() {
		return get("createUserId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
