package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponPublish<M extends BaseCouponPublish<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setPublishId(java.lang.String publishId) {
		set("publishId", publishId);
	}

	public java.lang.String getPublishId() {
		return get("publishId");
	}

	public void setCouponId(java.lang.String couponId) {
		set("couponId", couponId);
	}

	public java.lang.String getCouponId() {
		return get("couponId");
	}

	public void setBatchId(java.lang.Integer batchId) {
		set("batchId", batchId);
	}

	public java.lang.Integer getBatchId() {
		return get("batchId");
	}

	public void setLimitAmount(java.math.BigDecimal limitAmount) {
		set("limitAmount", limitAmount);
	}

	public java.math.BigDecimal getLimitAmount() {
		return get("limitAmount");
	}

	public void setLimitCount(java.lang.Integer limitCount) {
		set("limitCount", limitCount);
	}

	public java.lang.Integer getLimitCount() {
		return get("limitCount");
	}

	public void setCouponCount(java.lang.Integer couponCount) {
		set("couponCount", couponCount);
	}

	public java.lang.Integer getCouponCount() {
		return get("couponCount");
	}

	public void setUseStartTime(java.util.Date useStartTime) {
		set("useStartTime", useStartTime);
	}

	public java.util.Date getUseStartTime() {
		return get("useStartTime");
	}

	public void setUseEndTime(java.util.Date useEndTime) {
		set("useEndTime", useEndTime);
	}

	public java.util.Date getUseEndTime() {
		return get("useEndTime");
	}

	public void setStyleType(java.lang.Integer styleType) {
		set("styleType", styleType);
	}

	public java.lang.Integer getStyleType() {
		return get("styleType");
	}

	public void setUseType(java.lang.Integer useType) {
		set("useType", useType);
	}

	public java.lang.Integer getUseType() {
		return get("useType");
	}

	public void setUseTypeName(java.lang.String useTypeName) {
		set("useTypeName", useTypeName);
	}

	public java.lang.String getUseTypeName() {
		return get("useTypeName");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateIp(java.lang.String createIp) {
		set("createIp", createIp);
	}

	public java.lang.String getCreateIp() {
		return get("createIp");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.Integer getCreateUserId() {
		return get("createUserId");
	}

	public void setCreateUserName(java.lang.String createUserName) {
		set("createUserName", createUserName);
	}

	public java.lang.String getCreateUserName() {
		return get("createUserName");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
