package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImages<M extends BaseImages<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setImageId(java.lang.String imageId) {
		set("imageId", imageId);
	}

	public java.lang.String getImageId() {
		return get("imageId");
	}

	public void setShopId(java.lang.String shopId) {
		set("shopId", shopId);
	}

	public java.lang.String getShopId() {
		return get("shopId");
	}

	public void setWareId(java.lang.String wareId) {
		set("wareId", wareId);
	}

	public java.lang.String getWareId() {
		return get("wareId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setImageType(java.lang.Integer imageType) {
		set("imageType", imageType);
	}

	public java.lang.Integer getImageType() {
		return get("imageType");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("imageUrl");
	}

	public void setImageStatus(java.lang.Integer imageStatus) {
		set("imageStatus", imageStatus);
	}

	public java.lang.Integer getImageStatus() {
		return get("imageStatus");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.Integer getCreateUserId() {
		return get("createUserId");
	}

	public void setCreateUserName(java.lang.String createUserName) {
		set("createUserName", createUserName);
	}

	public java.lang.String getCreateUserName() {
		return get("createUserName");
	}

}
