package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setBuzId(java.lang.String buzId) {
		set("buzId", buzId);
	}

	public java.lang.String getBuzId() {
		return get("buzId");
	}

	public void setBuzIdType(java.lang.String buzIdType) {
		set("buzIdType", buzIdType);
	}

	public java.lang.String getBuzIdType() {
		return get("buzIdType");
	}

	public void setLogLevel(java.lang.Integer logLevel) {
		set("logLevel", logLevel);
	}

	public java.lang.Integer getLogLevel() {
		return get("logLevel");
	}

	public void setLogType(java.lang.String logType) {
		set("logType", logType);
	}

	public java.lang.String getLogType() {
		return get("logType");
	}

	public void setContent(byte[] content) {
		set("content", content);
	}

	public byte[] getContent() {
		return get("content");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
