package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setOrderUserName(java.lang.String orderUserName) {
		set("orderUserName", orderUserName);
	}

	public java.lang.String getOrderUserName() {
		return get("orderUserName");
	}

	public void setOrderAllAmount(java.math.BigDecimal orderAllAmount) {
		set("orderAllAmount", orderAllAmount);
	}

	public java.math.BigDecimal getOrderAllAmount() {
		return get("orderAllAmount");
	}

	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		set("orderAmount", orderAmount);
	}

	public java.math.BigDecimal getOrderAmount() {
		return get("orderAmount");
	}

	public void setPayAmount(java.math.BigDecimal payAmount) {
		set("payAmount", payAmount);
	}

	public java.math.BigDecimal getPayAmount() {
		return get("payAmount");
	}

	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discountAmount", discountAmount);
	}

	public java.math.BigDecimal getDiscountAmount() {
		return get("discountAmount");
	}

	public void setMobilePhone(java.lang.String mobilePhone) {
		set("mobilePhone", mobilePhone);
	}

	public java.lang.String getMobilePhone() {
		return get("mobilePhone");
	}

	public void setReceiveCountry(java.lang.String receiveCountry) {
		set("receiveCountry", receiveCountry);
	}

	public java.lang.String getReceiveCountry() {
		return get("receiveCountry");
	}

	public void setReceiveProvince(java.lang.String receiveProvince) {
		set("receiveProvince", receiveProvince);
	}

	public java.lang.String getReceiveProvince() {
		return get("receiveProvince");
	}

	public void setReceiveCity(java.lang.String receiveCity) {
		set("receiveCity", receiveCity);
	}

	public java.lang.String getReceiveCity() {
		return get("receiveCity");
	}

	public void setReceiveCounty(java.lang.String receiveCounty) {
		set("receiveCounty", receiveCounty);
	}

	public java.lang.String getReceiveCounty() {
		return get("receiveCounty");
	}

	public void setCommunityId(java.lang.Integer communityId) {
		set("communityId", communityId);
	}

	public java.lang.Integer getCommunityId() {
		return get("communityId");
	}

	public void setCommunity(java.lang.String community) {
		set("community", community);
	}

	public java.lang.String getCommunity() {
		return get("community");
	}

	public void setReceiveAddress(java.lang.String receiveAddress) {
		set("receiveAddress", receiveAddress);
	}

	public java.lang.String getReceiveAddress() {
		return get("receiveAddress");
	}

	public void setReceivePostNo(java.lang.String receivePostNo) {
		set("receivePostNo", receivePostNo);
	}

	public java.lang.String getReceivePostNo() {
		return get("receivePostNo");
	}

	public void setServiceStartTime(java.util.Date serviceStartTime) {
		set("serviceStartTime", serviceStartTime);
	}

	public java.util.Date getServiceStartTime() {
		return get("serviceStartTime");
	}

	public void setServiceEndTime(java.util.Date serviceEndTime) {
		set("serviceEndTime", serviceEndTime);
	}

	public java.util.Date getServiceEndTime() {
		return get("serviceEndTime");
	}

	public void setReceiveUserName(java.lang.String receiveUserName) {
		set("receiveUserName", receiveUserName);
	}

	public java.lang.String getReceiveUserName() {
		return get("receiveUserName");
	}

	public void setReceiverMobilePhone(java.lang.String receiverMobilePhone) {
		set("receiverMobilePhone", receiverMobilePhone);
	}

	public java.lang.String getReceiverMobilePhone() {
		return get("receiverMobilePhone");
	}

	public void setReceiveSex(java.lang.Integer receiveSex) {
		set("receiveSex", receiveSex);
	}

	public java.lang.Integer getReceiveSex() {
		return get("receiveSex");
	}

	public void setLeftEye(java.lang.String leftEye) {
		set("leftEye", leftEye);
	}

	public java.lang.String getLeftEye() {
		return get("leftEye");
	}

	public void setRightEye(java.lang.String rightEye) {
		set("rightEye", rightEye);
	}

	public java.lang.String getRightEye() {
		return get("rightEye");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("orderStatus", orderStatus);
	}

	public java.lang.Integer getOrderStatus() {
		return get("orderStatus");
	}

	public void setOrderType(java.lang.Integer orderType) {
		set("orderType", orderType);
	}

	public java.lang.Integer getOrderType() {
		return get("orderType");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

	public void setPayStatus(java.lang.Integer payStatus) {
		set("payStatus", payStatus);
	}

	public java.lang.Integer getPayStatus() {
		return get("payStatus");
	}

	public void setIsCallBack(java.lang.Integer isCallBack) {
		set("isCallBack", isCallBack);
	}

	public java.lang.Integer getIsCallBack() {
		return get("isCallBack");
	}

	public void setDeliveryType(java.lang.Integer deliveryType) {
		set("deliveryType", deliveryType);
	}

	public java.lang.Integer getDeliveryType() {
		return get("deliveryType");
	}

	public void setDeliveryUserId(java.lang.Integer deliveryUserId) {
		set("deliveryUserId", deliveryUserId);
	}

	public java.lang.Integer getDeliveryUserId() {
		return get("deliveryUserId");
	}

	public void setDeliveryUserName(java.lang.String deliveryUserName) {
		set("deliveryUserName", deliveryUserName);
	}

	public java.lang.String getDeliveryUserName() {
		return get("deliveryUserName");
	}

	public void setDeliveryPhone(java.lang.String deliveryPhone) {
		set("deliveryPhone", deliveryPhone);
	}

	public java.lang.String getDeliveryPhone() {
		return get("deliveryPhone");
	}

	public void setJsUserId(java.lang.Integer jsUserId) {
		set("jsUserId", jsUserId);
	}

	public java.lang.Integer getJsUserId() {
		return get("jsUserId");
	}

	public void setJsUserName(java.lang.String jsUserName) {
		set("jsUserName", jsUserName);
	}

	public java.lang.String getJsUserName() {
		return get("jsUserName");
	}

	public void setRealServiceStartTime(java.util.Date realServiceStartTime) {
		set("realServiceStartTime", realServiceStartTime);
	}

	public java.util.Date getRealServiceStartTime() {
		return get("realServiceStartTime");
	}

	public void setRealServiceEndTime(java.util.Date realServiceEndTime) {
		set("realServiceEndTime", realServiceEndTime);
	}

	public java.util.Date getRealServiceEndTime() {
		return get("realServiceEndTime");
	}

	public void setJsPhone(java.lang.String jsPhone) {
		set("jsPhone", jsPhone);
	}

	public java.lang.String getJsPhone() {
		return get("jsPhone");
	}

	public void setIsEvaluate(java.lang.Integer isEvaluate) {
		set("isEvaluate", isEvaluate);
	}

	public java.lang.Integer getIsEvaluate() {
		return get("isEvaluate");
	}

	public void setIsJsEvaluate(java.lang.Integer isJsEvaluate) {
		set("isJsEvaluate", isJsEvaluate);
	}

	public java.lang.Integer getIsJsEvaluate() {
		return get("isJsEvaluate");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCsRemark(java.lang.String csRemark) {
		set("csRemark", csRemark);
	}

	public java.lang.String getCsRemark() {
		return get("csRemark");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setAutoTimestamp(java.util.Date autoTimestamp) {
		set("autoTimestamp", autoTimestamp);
	}

	public java.util.Date getAutoTimestamp() {
		return get("autoTimestamp");
	}

}
