package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setJsId(java.lang.Integer jsId) {
		set("jsId", jsId);
	}

	public java.lang.Integer getJsId() {
		return get("jsId");
	}

	public void setJsName(java.lang.String jsName) {
		set("jsName", jsName);
	}

	public java.lang.String getJsName() {
		return get("jsName");
	}

	public void setFbType(java.lang.Integer fbType) {
		set("fbType", fbType);
	}

	public java.lang.Integer getFbType() {
		return get("fbType");
	}

	public void setLeftVision(java.lang.String leftVision) {
		set("leftVision", leftVision);
	}

	public java.lang.String getLeftVision() {
		return get("leftVision");
	}

	public void setRightVision(java.lang.String rightVision) {
		set("rightVision", rightVision);
	}

	public java.lang.String getRightVision() {
		return get("rightVision");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

	public void setAixin(java.lang.Integer aixin) {
		set("aixin", aixin);
	}

	public java.lang.Integer getAixin() {
		return get("aixin");
	}

	public void setXixin(java.lang.Integer xixin) {
		set("xixin", xixin);
	}

	public java.lang.Integer getXixin() {
		return get("xixin");
	}

	public void setNaixin(java.lang.Integer naixin) {
		set("naixin", naixin);
	}

	public java.lang.Integer getNaixin() {
		return get("naixin");
	}

	public void setHulinengli(java.lang.Integer hulinengli) {
		set("hulinengli", hulinengli);
	}

	public java.lang.Integer getHulinengli() {
		return get("hulinengli");
	}

	public void setJiazhengnengli(java.lang.Integer jiazhengnengli) {
		set("jiazhengnengli", jiazhengnengli);
	}

	public java.lang.Integer getJiazhengnengli() {
		return get("jiazhengnengli");
	}

	public void setServiceEffect(java.lang.Integer serviceEffect) {
		set("serviceEffect", serviceEffect);
	}

	public java.lang.Integer getServiceEffect() {
		return get("serviceEffect");
	}

	public void setDoctorName(java.lang.String doctorName) {
		set("doctorName", doctorName);
	}

	public java.lang.String getDoctorName() {
		return get("doctorName");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("checkTime", checkTime);
	}

	public java.util.Date getCheckTime() {
		return get("checkTime");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreatorId(java.lang.Integer creatorId) {
		set("creatorId", creatorId);
	}

	public java.lang.Integer getCreatorId() {
		return get("creatorId");
	}

	public void setCreatorName(java.lang.String creatorName) {
		set("creatorName", creatorName);
	}

	public java.lang.String getCreatorName() {
		return get("creatorName");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
