package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSsBind<M extends BaseSsBind<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setShopId(java.lang.String shopId) {
		set("shopId", shopId);
	}

	public java.lang.String getShopId() {
		return get("shopId");
	}

	public void setSnsId(java.lang.String snsId) {
		set("snsId", snsId);
	}

	public java.lang.String getSnsId() {
		return get("snsId");
	}

	public void setBindTime(java.util.Date bindTime) {
		set("bindTime", bindTime);
	}

	public java.util.Date getBindTime() {
		return get("bindTime");
	}

}
