package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAddress<M extends BaseUserAddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setReceiveUserName(java.lang.String receiveUserName) {
		set("receiveUserName", receiveUserName);
	}

	public java.lang.String getReceiveUserName() {
		return get("receiveUserName");
	}

	public void setReceiveMobilePhone(java.lang.String receiveMobilePhone) {
		set("receiveMobilePhone", receiveMobilePhone);
	}

	public java.lang.String getReceiveMobilePhone() {
		return get("receiveMobilePhone");
	}

	public void setReceiveSnsId(java.lang.String receiveSnsId) {
		set("receiveSnsId", receiveSnsId);
	}

	public java.lang.String getReceiveSnsId() {
		return get("receiveSnsId");
	}

	public void setReceiveCountry(java.lang.String receiveCountry) {
		set("receiveCountry", receiveCountry);
	}

	public java.lang.String getReceiveCountry() {
		return get("receiveCountry");
	}

	public void setReceiveProvince(java.lang.String receiveProvince) {
		set("receiveProvince", receiveProvince);
	}

	public java.lang.String getReceiveProvince() {
		return get("receiveProvince");
	}

	public void setReceiveCity(java.lang.String receiveCity) {
		set("receiveCity", receiveCity);
	}

	public java.lang.String getReceiveCity() {
		return get("receiveCity");
	}

	public void setReceiveCounty(java.lang.String receiveCounty) {
		set("receiveCounty", receiveCounty);
	}

	public java.lang.String getReceiveCounty() {
		return get("receiveCounty");
	}

	public void setReceiveAddress(java.lang.String receiveAddress) {
		set("receiveAddress", receiveAddress);
	}

	public java.lang.String getReceiveAddress() {
		return get("receiveAddress");
	}

	public void setReceivePostNo(java.lang.String receivePostNo) {
		set("receivePostNo", receivePostNo);
	}

	public java.lang.String getReceivePostNo() {
		return get("receivePostNo");
	}

	public void setIsDefault(java.lang.Integer isDefault) {
		set("isDefault", isDefault);
	}

	public java.lang.Integer getIsDefault() {
		return get("isDefault");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.Integer getCreateUserId() {
		return get("createUserId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
