package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCouponId(java.lang.String couponId) {
		set("couponId", couponId);
	}

	public java.lang.String getCouponId() {
		return get("couponId");
	}

	public void setShopId(java.lang.String shopId) {
		set("shopId", shopId);
	}

	public java.lang.String getShopId() {
		return get("shopId");
	}

	public void setShopName(java.lang.String shopName) {
		set("shopName", shopName);
	}

	public java.lang.String getShopName() {
		return get("shopName");
	}

	public void setBuzLine(java.lang.Integer buzLine) {
		set("buzLine", buzLine);
	}

	public java.lang.Integer getBuzLine() {
		return get("buzLine");
	}

	public void setBuzLineName(java.lang.String buzLineName) {
		set("buzLineName", buzLineName);
	}

	public java.lang.String getBuzLineName() {
		return get("buzLineName");
	}

	public void setCouponName(java.lang.String couponName) {
		set("couponName", couponName);
	}

	public java.lang.String getCouponName() {
		return get("couponName");
	}

	public void setCouponAmount(java.math.BigDecimal couponAmount) {
		set("couponAmount", couponAmount);
	}

	public java.math.BigDecimal getCouponAmount() {
		return get("couponAmount");
	}

	public void setCouponType(java.lang.Integer couponType) {
		set("couponType", couponType);
	}

	public java.lang.Integer getCouponType() {
		return get("couponType");
	}

	public void setStyleType(java.lang.Integer styleType) {
		set("styleType", styleType);
	}

	public java.lang.Integer getStyleType() {
		return get("styleType");
	}

	public void setCouponStatus(java.lang.Integer couponStatus) {
		set("couponStatus", couponStatus);
	}

	public java.lang.Integer getCouponStatus() {
		return get("couponStatus");
	}

	public void setDescript(java.lang.String descript) {
		set("descript", descript);
	}

	public java.lang.String getDescript() {
		return get("descript");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateIp(java.lang.String createIp) {
		set("createIp", createIp);
	}

	public java.lang.String getCreateIp() {
		return get("createIp");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.Integer getCreateUserId() {
		return get("createUserId");
	}

	public void setCreateUserName(java.lang.String createUserName) {
		set("createUserName", createUserName);
	}

	public java.lang.String getCreateUserName() {
		return get("createUserName");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
