package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setFromUserId(java.lang.Integer fromUserId) {
		set("fromUserId", fromUserId);
	}

	public java.lang.Integer getFromUserId() {
		return get("fromUserId");
	}

	public void setToUserId(java.lang.Integer toUserId) {
		set("toUserId", toUserId);
	}

	public java.lang.Integer getToUserId() {
		return get("toUserId");
	}

	public void setMessageType(java.lang.Integer messageType) {
		set("messageType", messageType);
	}

	public java.lang.Integer getMessageType() {
		return get("messageType");
	}

	public void setMessageStatus(java.lang.Integer messageStatus) {
		set("messageStatus", messageStatus);
	}

	public java.lang.Integer getMessageStatus() {
		return get("messageStatus");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
