package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseAdminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUser extends BaseAdminUser<AdminUser> {
	public static final AdminUser dao = new AdminUser();
}
