package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseAreaGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AreaGroup extends BaseAreaGroup<AreaGroup> {
	public static final AreaGroup dao = new AreaGroup();
}
