package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseAuBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuBind extends BaseAuBind<AuBind> {
	public static final AuBind dao = new AuBind();
}
