package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category();
}
