package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City();
}
