package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseCommonUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonUser extends BaseCommonUser<CommonUser> {
	public static final CommonUser dao = new CommonUser();
}
