package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseCouponUse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponUse extends BaseCouponUse<CouponUse> {
	public static final CouponUse dao = new CouponUse();
}
