package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseCouponPublish;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponPublish extends BaseCouponPublish<CouponPublish> {
	public static final CouponPublish dao = new CouponPublish();
}
