package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseDic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dic extends BaseDic<Dic> {
	public static final Dic dao = new Dic();
}
