package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	public static final Feedback dao = new Feedback();
}
