package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseHisOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HisOrder extends BaseHisOrder<HisOrder> {
	public static final HisOrder dao = new HisOrder();
}
