package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseHoliday;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Holiday extends BaseHoliday<Holiday> {
	public static final Holiday dao = new Holiday();
}
