package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Images extends BaseImages<Images> {
	public static final Images dao = new Images();
}
