package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Info extends BaseInfo<Info> {
	public static final Info dao = new Info();
}
