package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	public static final Log dao = new Log();
}
