package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order();
}
