package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BasePayTransaction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayTransaction extends BasePayTransaction<PayTransaction> {
	public static final PayTransaction dao = new PayTransaction();
}
