package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop();
}
