package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseSsBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SsBind extends BaseSsBind<SsBind> {
	public static final SsBind dao = new SsBind();
}
