package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseSuBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuBind extends BaseSuBind<SuBind> {
	public static final SuBind dao = new SuBind();
}
