package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseSuborder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suborder extends BaseSuborder<Suborder> {
	public static final Suborder dao = new Suborder();
}
