package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseUserBalance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBalance extends BaseUserBalance<UserBalance> {
	public static final UserBalance dao = new UserBalance();
}
