package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseUserAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAddress extends BaseUserAddress<UserAddress> {
	public static final UserAddress dao = new UserAddress();
}
