package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseValidateCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ValidateCode extends BaseValidateCode<ValidateCode> {
	public static final ValidateCode dao = new ValidateCode();
}
