package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseWareStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WareStore extends BaseWareStore<WareStore> {
	public static final WareStore dao = new WareStore();
}
