package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseWarePrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WarePrice extends BaseWarePrice<WarePrice> {
	public static final WarePrice dao = new WarePrice();
}
