package cn.singno.jfinal.demo.model;

import cn.singno.jfinal.demo.model.base.BaseWare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ware extends BaseWare<Ware> {
	public static final Ware dao = new Ware();
}
