package cn.singno.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommonUser<M extends BaseCommonUser<M>> extends Model<M> {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public void setMobilePhone(java.lang.String mobilePhone) {
		set("mobilePhone", mobilePhone);
	}

	public java.lang.String getMobilePhone() {
		return get("mobilePhone");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}

	public java.lang.String getNickName() {
		return get("nickName");
	}

	public void setWeChat(java.lang.String weChat) {
		set("weChat", weChat);
	}

	public java.lang.String getWeChat() {
		return get("weChat");
	}

	public void setUserNo(java.lang.String userNo) {
		set("userNo", userNo);
	}

	public java.lang.String getUserNo() {
		return get("userNo");
	}

	public void setUserType(java.lang.Integer userType) {
		set("userType", userType);
	}

	public java.lang.Integer getUserType() {
		return get("userType");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setNative(java.lang.String _native) {
		set("native", _native);
	}

	public java.lang.String getNative() {
		return get("native");
	}

	public void setCateId(java.lang.String cateId) {
		set("cateId", cateId);
	}

	public java.lang.String getCateId() {
		return get("cateId");
	}

	public void setCateName(java.lang.String cateName) {
		set("cateName", cateName);
	}

	public java.lang.String getCateName() {
		return get("cateName");
	}

	public void setServiceCityId(java.lang.Integer serviceCityId) {
		set("serviceCityId", serviceCityId);
	}

	public java.lang.Integer getServiceCityId() {
		return get("serviceCityId");
	}

	public void setServiceCityName(java.lang.String serviceCityName) {
		set("serviceCityName", serviceCityName);
	}

	public java.lang.String getServiceCityName() {
		return get("serviceCityName");
	}

	public void setSpeciality(java.lang.String speciality) {
		set("speciality", speciality);
	}

	public java.lang.String getSpeciality() {
		return get("speciality");
	}

	public void setMandarin(java.lang.Integer mandarin) {
		set("mandarin", mandarin);
	}

	public java.lang.Integer getMandarin() {
		return get("mandarin");
	}

	public void setLocalism(java.lang.String localism) {
		set("localism", localism);
	}

	public java.lang.String getLocalism() {
		return get("localism");
	}

	public void setStars(java.lang.Integer stars) {
		set("stars", stars);
	}

	public java.lang.Integer getStars() {
		return get("stars");
	}

	public void setReligion(java.lang.String religion) {
		set("religion", religion);
	}

	public java.lang.String getReligion() {
		return get("religion");
	}

	public void setWorkage(java.lang.Integer workage) {
		set("workage", workage);
	}

	public java.lang.Integer getWorkage() {
		return get("workage");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setIsLeader(java.lang.Integer isLeader) {
		set("isLeader", isLeader);
	}

	public java.lang.Integer getIsLeader() {
		return get("isLeader");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setYn(java.lang.Integer yn) {
		set("yn", yn);
	}

	public java.lang.Integer getYn() {
		return get("yn");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
